apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: airflow
type: Opaque
data:
  # Replace below with base64-encoded values
  username: YWRtaW4=       # "admin"  - temporary username
  password: cGFzc3dvcmQ=   # "password" - temporary password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgresql
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgresql
  template:
    metadata:
      labels:
        app: airflow-postgresql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-pool-name
                operator: In
                values:
                - core-c2d-highcpu-4
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      # volumes should be at the same level as containers
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql
  namespace: airflow
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: airflow-postgresql
