nameOverride: ""

image:
  registry: docker.io
  repository: kubeflow/spark-operator
  tag: "2.1.0"
  pullPolicy: IfNotPresent

spark:
  jobNamespaces:
  - spark

controller:
  replicas: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-pool-name
            operator: In
            values:
            - core-c2d-highcpu-4

webhook:
  replicas: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-pool-name
            operator: In
            values:
            - core-c2d-highcpu-4

prometheus:
  metrics:
    enable: false